name: Docker Build and Push
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to GitHub Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Build and Push Docker Image
      run: |
        docker build -t docker.pkg.github.com/${{ github.repository }}/prom-auto-record:latest .
        docker push docker.pkg.github.com/${{ github.repository }}/prom-auto-record:latest
